/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PostJobRouteImport } from './routes/post-job'
import { Route as MyJobsRouteImport } from './routes/my-jobs'
import { Route as FindJobsRouteImport } from './routes/find-jobs'
import { Route as EscrowWalletRouteImport } from './routes/escrow-wallet'
import { Route as DisputesRouteImport } from './routes/disputes'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobIdRouteImport } from './routes/job.$id'
import { Route as DashboardWorkerRouteImport } from './routes/dashboard.worker'
import { Route as DashboardCustomerRouteImport } from './routes/dashboard.customer'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PostJobRoute = PostJobRouteImport.update({
  id: '/post-job',
  path: '/post-job',
  getParentRoute: () => rootRouteImport,
} as any)
const MyJobsRoute = MyJobsRouteImport.update({
  id: '/my-jobs',
  path: '/my-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const FindJobsRoute = FindJobsRouteImport.update({
  id: '/find-jobs',
  path: '/find-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const EscrowWalletRoute = EscrowWalletRouteImport.update({
  id: '/escrow-wallet',
  path: '/escrow-wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputesRoute = DisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobIdRoute = JobIdRouteImport.update({
  id: '/job/$id',
  path: '/job/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkerRoute = DashboardWorkerRouteImport.update({
  id: '/dashboard/worker',
  path: '/dashboard/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCustomerRoute = DashboardCustomerRouteImport.update({
  id: '/dashboard/customer',
  path: '/dashboard/customer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/disputes': typeof DisputesRoute
  '/escrow-wallet': typeof EscrowWalletRoute
  '/find-jobs': typeof FindJobsRoute
  '/my-jobs': typeof MyJobsRoute
  '/post-job': typeof PostJobRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/customer': typeof DashboardCustomerRoute
  '/dashboard/worker': typeof DashboardWorkerRoute
  '/job/$id': typeof JobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/disputes': typeof DisputesRoute
  '/escrow-wallet': typeof EscrowWalletRoute
  '/find-jobs': typeof FindJobsRoute
  '/my-jobs': typeof MyJobsRoute
  '/post-job': typeof PostJobRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/customer': typeof DashboardCustomerRoute
  '/dashboard/worker': typeof DashboardWorkerRoute
  '/job/$id': typeof JobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/disputes': typeof DisputesRoute
  '/escrow-wallet': typeof EscrowWalletRoute
  '/find-jobs': typeof FindJobsRoute
  '/my-jobs': typeof MyJobsRoute
  '/post-job': typeof PostJobRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/customer': typeof DashboardCustomerRoute
  '/dashboard/worker': typeof DashboardWorkerRoute
  '/job/$id': typeof JobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/disputes'
    | '/escrow-wallet'
    | '/find-jobs'
    | '/my-jobs'
    | '/post-job'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/customer'
    | '/dashboard/worker'
    | '/job/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/disputes'
    | '/escrow-wallet'
    | '/find-jobs'
    | '/my-jobs'
    | '/post-job'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/customer'
    | '/dashboard/worker'
    | '/job/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/disputes'
    | '/escrow-wallet'
    | '/find-jobs'
    | '/my-jobs'
    | '/post-job'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/customer'
    | '/dashboard/worker'
    | '/job/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DisputesRoute: typeof DisputesRoute
  EscrowWalletRoute: typeof EscrowWalletRoute
  FindJobsRoute: typeof FindJobsRoute
  MyJobsRoute: typeof MyJobsRoute
  PostJobRoute: typeof PostJobRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  DashboardCustomerRoute: typeof DashboardCustomerRoute
  DashboardWorkerRoute: typeof DashboardWorkerRoute
  JobIdRoute: typeof JobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-job': {
      id: '/post-job'
      path: '/post-job'
      fullPath: '/post-job'
      preLoaderRoute: typeof PostJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-jobs': {
      id: '/my-jobs'
      path: '/my-jobs'
      fullPath: '/my-jobs'
      preLoaderRoute: typeof MyJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-jobs': {
      id: '/find-jobs'
      path: '/find-jobs'
      fullPath: '/find-jobs'
      preLoaderRoute: typeof FindJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escrow-wallet': {
      id: '/escrow-wallet'
      path: '/escrow-wallet'
      fullPath: '/escrow-wallet'
      preLoaderRoute: typeof EscrowWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disputes': {
      id: '/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof DisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job/$id': {
      id: '/job/$id'
      path: '/job/$id'
      fullPath: '/job/$id'
      preLoaderRoute: typeof JobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/worker': {
      id: '/dashboard/worker'
      path: '/dashboard/worker'
      fullPath: '/dashboard/worker'
      preLoaderRoute: typeof DashboardWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/customer': {
      id: '/dashboard/customer'
      path: '/dashboard/customer'
      fullPath: '/dashboard/customer'
      preLoaderRoute: typeof DashboardCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DisputesRoute: DisputesRoute,
  EscrowWalletRoute: EscrowWalletRoute,
  FindJobsRoute: FindJobsRoute,
  MyJobsRoute: MyJobsRoute,
  PostJobRoute: PostJobRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  DashboardCustomerRoute: DashboardCustomerRoute,
  DashboardWorkerRoute: DashboardWorkerRoute,
  JobIdRoute: JobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
